In [1]:
import numpy as np
import pandas as pd
Incident=pd.read_csv(r"C:\Users\agrabia\Documents\Formation\Projet/LFB Incident data Last 3 years.csv")
Mobilisation=pd.read_csv(r"C:\Users\agrabia\Documents\Formation\Projet/LFB Mobilisation data Last 3 years.csv", sep=';')
Coordonnees_brigade=pd.read_csv(r"C:\Users\agrabia\Documents\Formation\Projet/LondonFireBrigade_Coordonnées.csv",sep=';')

In [2]:
Incident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381366 entries, 0 to 381365
Data columns (total 39 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   IncidentNumber                          381366 non-null  object
 1   DateOfCall                              381366 non-null  object
 2   CalYear                                 381366 non-null  int64
 3   TimeOfCall                              381366 non-null  object
 4   HourOfCall                              381366 non-null  int64
 5   IncidentGroup                           381366 non-null  object
 6   StopCodeDescription                     381366 non-null  object
 7   SpecialServiceType                      136659 non-null  object
 8   PropertyCategory                        381366 non-null  object
 9   PropertyType                            381366 non-null  object
 10  AddressQualifier                        381366 non-null  object
 11  Postcode_full                           165833 non-null  object
 12  Postcode_district                       381366 non-null  object
 13  UPRN                                    381366 non-null  int64
 14  USRN                                    381366 non-null  int64
 15  IncGeo_BoroughCode                      381366 non-null  object
 16  IncGeo_BoroughName                      381366 non-null  object
 17  ProperCase                              381366 non-null  object
 18  IncGeo_WardCode                         381360 non-null  object
 19  IncGeo_WardName                         381360 non-null  object
 20  IncGeo_WardNameNew                      381360 non-null  object
 21  Easting_m                               165833 non-null  float64
 22  Northing_m                              165833 non-null  float64
 23  Easting_rounded                         381366 non-null  int64
 24  Northing_rounded                        381366 non-null  int64
 25  Latitude                                165833 non-null  float64
 26  Longitude                               165833 non-null  float64
 27  FRS                                     381366 non-null  object
 28  IncidentStationGround                   381365 non-null  object
 29  FirstPumpArriving_AttendanceTime        359041 non-null  float64
 30  FirstPumpArriving_DeployedFromStation   359036 non-null  object
 31  SecondPumpArriving_AttendanceTime       139168 non-null  float64
 32  SecondPumpArriving_DeployedFromStation  139166 non-null  object
 33  NumStationsWithPumpsAttending           375902 non-null  float64
 34  NumPumpsAttending                       375902 non-null  float64
 35  PumpCount                               378169 non-null  float64
 36  PumpHoursRoundUp                        378065 non-null  float64
 37  Notional Cost (£)                       378065 non-null  float64
 38  NumCalls                                381363 non-null  float64
dtypes: float64(12), int64(6), object(21)
memory usage: 113.5+ MB

In [3]:
Mobilisation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560529 entries, 0 to 560528
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   IncidentNumber            560529 non-null  object
 1   CalYear                   560529 non-null  int64
 2   HourOfCall                560529 non-null  int64
 3   ResourceMobilisationId    560529 non-null  int64
 4   Resource_Code             560529 non-null  object
 5   PerformanceReporting      560529 non-null  object
 6   DateAndTimeMobilised      560529 non-null  object
 7   DateAndTimeMobile         558164 non-null  object
 8   DateAndTimeArrived        560529 non-null  object
 9   TurnoutTimeSeconds        558152 non-null  float64
 10  TravelTimeSeconds         558148 non-null  float64
 11  AttendanceTimeSeconds     560529 non-null  int64
 12  DateAndTimeLeft           560292 non-null  object
 13  DateAndTimeReturned       0 non-null       float64
 14  DeployedFromStation_Code  560520 non-null  object
 15  DeployedFromStation_Name  560520 non-null  object
 16  DeployedFromLocation      560127 non-null  object
 17  PumpOrder                 560529 non-null  int64
 18  PlusCode_Code             560529 non-null  object
 19  PlusCode_Description      560529 non-null  object
 20  DelayCodeId               128158 non-null  float64
 21  DelayCode_Description     128158 non-null  object
dtypes: float64(4), int64(5), object(13)
memory usage: 94.1+ MB

In [4]:
Mobilisation_1=Mobilisation[Mobilisation['PerformanceReporting']=='1']

In [5]:
Mobilisation_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 361082 entries, 0 to 560528
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   IncidentNumber            361082 non-null  object
 1   CalYear                   361082 non-null  int64
 2   HourOfCall                361082 non-null  int64
 3   ResourceMobilisationId    361082 non-null  int64
 4   Resource_Code             361082 non-null  object
 5   PerformanceReporting      361082 non-null  object
 6   DateAndTimeMobilised      361082 non-null  object
 7   DateAndTimeMobile         359135 non-null  object
 8   DateAndTimeArrived        361082 non-null  object
 9   TurnoutTimeSeconds        359129 non-null  float64
 10  TravelTimeSeconds         359121 non-null  float64
 11  AttendanceTimeSeconds     361082 non-null  int64
 12  DateAndTimeLeft           360920 non-null  object
 13  DateAndTimeReturned       0 non-null       float64
 14  DeployedFromStation_Code  361076 non-null  object
 15  DeployedFromStation_Name  361076 non-null  object
 16  DeployedFromLocation      360817 non-null  object
 17  PumpOrder                 361082 non-null  int64
 18  PlusCode_Code             361082 non-null  object
 19  PlusCode_Description      361082 non-null  object
 20  DelayCodeId               99717 non-null   float64
 21  DelayCode_Description     99717 non-null   object
dtypes: float64(4), int64(5), object(13)
memory usage: 63.4+ MB

In [6]:
Mobilisation_1.drop(['CalYear','HourOfCall'], axis=1,inplace=True)
Final_1=Incident.merge(right=Mobilisation_1, on='IncidentNumber')
Final_1.info()

C:\Users\agrabia\AppData\Local\Temp\ipykernel_18276\1996949902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Mobilisation_1.drop(['CalYear','HourOfCall'], axis=1,inplace=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 359042 entries, 0 to 359041
Data columns (total 58 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   IncidentNumber                          359042 non-null  object
 1   DateOfCall                              359042 non-null  object
 2   CalYear                                 359042 non-null  int64
 3   TimeOfCall                              359042 non-null  object
 4   HourOfCall                              359042 non-null  int64
 5   IncidentGroup                           359042 non-null  object
 6   StopCodeDescription                     359042 non-null  object
 7   SpecialServiceType                      116516 non-null  object
 8   PropertyCategory                        359042 non-null  object
 9   PropertyType                            359042 non-null  object
 10  AddressQualifier                        359042 non-null  object
 11  Postcode_full                           160205 non-null  object
 12  Postcode_district                       359042 non-null  object
 13  UPRN                                    359042 non-null  int64
 14  USRN                                    359042 non-null  int64
 15  IncGeo_BoroughCode                      359042 non-null  object
 16  IncGeo_BoroughName                      359042 non-null  object
 17  ProperCase                              359042 non-null  object
 18  IncGeo_WardCode                         359036 non-null  object
 19  IncGeo_WardName                         359036 non-null  object
 20  IncGeo_WardNameNew                      359036 non-null  object
 21  Easting_m                               160205 non-null  float64
 22  Northing_m                              160205 non-null  float64
 23  Easting_rounded                         359042 non-null  int64
 24  Northing_rounded                        359042 non-null  int64
 25  Latitude                                160205 non-null  float64
 26  Longitude                               160205 non-null  float64
 27  FRS                                     359042 non-null  object
 28  IncidentStationGround                   359041 non-null  object
 29  FirstPumpArriving_AttendanceTime        359041 non-null  float64
 30  FirstPumpArriving_DeployedFromStation   359036 non-null  object
 31  SecondPumpArriving_AttendanceTime       139168 non-null  float64
 32  SecondPumpArriving_DeployedFromStation  139166 non-null  object
 33  NumStationsWithPumpsAttending           359042 non-null  float64
 34  NumPumpsAttending                       359042 non-null  float64
 35  PumpCount                               359042 non-null  float64
 36  PumpHoursRoundUp                        358956 non-null  float64
 37  Notional Cost (£)                       358956 non-null  float64
 38  NumCalls                                359041 non-null  float64
 39  ResourceMobilisationId                  359042 non-null  int64
 40  Resource_Code                           359042 non-null  object
 41  PerformanceReporting                    359042 non-null  object
 42  DateAndTimeMobilised                    359042 non-null  object
 43  DateAndTimeMobile                       357120 non-null  object
 44  DateAndTimeArrived                      359042 non-null  object
 45  TurnoutTimeSeconds                      357114 non-null  float64
 46  TravelTimeSeconds                       357106 non-null  float64
 47  AttendanceTimeSeconds                   359042 non-null  int64
 48  DateAndTimeLeft                         358883 non-null  object
 49  DateAndTimeReturned                     0 non-null       float64
 50  DeployedFromStation_Code                359037 non-null  object
 51  DeployedFromStation_Name                359037 non-null  object
 52  DeployedFromLocation                    358777 non-null  object
 53  PumpOrder                               359042 non-null  int64
 54  PlusCode_Code                           359042 non-null  object
 55  PlusCode_Description                    359042 non-null  object
 56  DelayCodeId                             98075 non-null   float64
 57  DelayCode_Description                   98075 non-null   object
dtypes: float64(16), int64(9), object(33)
memory usage: 161.6+ MB

In [7]:
Final_1['DateOfCall_bis'] = pd.to_datetime(Final_1['DateOfCall'])
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 359042 entries, 0 to 359041
Data columns (total 59 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   IncidentNumber                          359042 non-null  object
 1   DateOfCall                              359042 non-null  object
 2   CalYear                                 359042 non-null  int64
 3   TimeOfCall                              359042 non-null  object
 4   HourOfCall                              359042 non-null  int64
 5   IncidentGroup                           359042 non-null  object
 6   StopCodeDescription                     359042 non-null  object
 7   SpecialServiceType                      116516 non-null  object
 8   PropertyCategory                        359042 non-null  object
 9   PropertyType                            359042 non-null  object
 10  AddressQualifier                        359042 non-null  object
 11  Postcode_full                           160205 non-null  object
 12  Postcode_district                       359042 non-null  object
 13  UPRN                                    359042 non-null  int64
 14  USRN                                    359042 non-null  int64
 15  IncGeo_BoroughCode                      359042 non-null  object
 16  IncGeo_BoroughName                      359042 non-null  object
 17  ProperCase                              359042 non-null  object
 18  IncGeo_WardCode                         359036 non-null  object
 19  IncGeo_WardName                         359036 non-null  object
 20  IncGeo_WardNameNew                      359036 non-null  object
 21  Easting_m                               160205 non-null  float64
 22  Northing_m                              160205 non-null  float64
 23  Easting_rounded                         359042 non-null  int64
 24  Northing_rounded                        359042 non-null  int64
 25  Latitude                                160205 non-null  float64
 26  Longitude                               160205 non-null  float64
 27  FRS                                     359042 non-null  object
 28  IncidentStationGround                   359041 non-null  object
 29  FirstPumpArriving_AttendanceTime        359041 non-null  float64
 30  FirstPumpArriving_DeployedFromStation   359036 non-null  object
 31  SecondPumpArriving_AttendanceTime       139168 non-null  float64
 32  SecondPumpArriving_DeployedFromStation  139166 non-null  object
 33  NumStationsWithPumpsAttending           359042 non-null  float64
 34  NumPumpsAttending                       359042 non-null  float64
 35  PumpCount                               359042 non-null  float64
 36  PumpHoursRoundUp                        358956 non-null  float64
 37  Notional Cost (£)                       358956 non-null  float64
 38  NumCalls                                359041 non-null  float64
 39  ResourceMobilisationId                  359042 non-null  int64
 40  Resource_Code                           359042 non-null  object
 41  PerformanceReporting                    359042 non-null  object
 42  DateAndTimeMobilised                    359042 non-null  object
 43  DateAndTimeMobile                       357120 non-null  object
 44  DateAndTimeArrived                      359042 non-null  object
 45  TurnoutTimeSeconds                      357114 non-null  float64
 46  TravelTimeSeconds                       357106 non-null  float64
 47  AttendanceTimeSeconds                   359042 non-null  int64
 48  DateAndTimeLeft                         358883 non-null  object
 49  DateAndTimeReturned                     0 non-null       float64
 50  DeployedFromStation_Code                359037 non-null  object
 51  DeployedFromStation_Name                359037 non-null  object
 52  DeployedFromLocation                    358777 non-null  object
 53  PumpOrder                               359042 non-null  int64
 54  PlusCode_Code                           359042 non-null  object
 55  PlusCode_Description                    359042 non-null  object
 56  DelayCodeId                             98075 non-null   float64
 57  DelayCode_Description                   98075 non-null   object
 58  DateOfCall_bis                          359042 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(16), int64(9), object(33)
memory usage: 164.4+ MB

In [8]:
Final_1.drop(['DateOfCall','DateAndTimeReturned'], axis=1,inplace=True)

In [9]:
def get_minut(date):
    time_decoupe=date.split(':')
    return date.split(':')[1]
Final_1['MinuteOfCall'] = Final_1['TimeOfCall'].apply(get_minut)
Final_1['MinuteOfCall']=Final_1['MinuteOfCall'].astype(int)
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 359042 entries, 0 to 359041
Data columns (total 58 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   IncidentNumber                          359042 non-null  object
 1   CalYear                                 359042 non-null  int64
 2   TimeOfCall                              359042 non-null  object
 3   HourOfCall                              359042 non-null  int64
 4   IncidentGroup                           359042 non-null  object
 5   StopCodeDescription                     359042 non-null  object
 6   SpecialServiceType                      116516 non-null  object
 7   PropertyCategory                        359042 non-null  object
 8   PropertyType                            359042 non-null  object
 9   AddressQualifier                        359042 non-null  object
 10  Postcode_full                           160205 non-null  object
 11  Postcode_district                       359042 non-null  object
 12  UPRN                                    359042 non-null  int64
 13  USRN                                    359042 non-null  int64
 14  IncGeo_BoroughCode                      359042 non-null  object
 15  IncGeo_BoroughName                      359042 non-null  object
 16  ProperCase                              359042 non-null  object
 17  IncGeo_WardCode                         359036 non-null  object
 18  IncGeo_WardName                         359036 non-null  object
 19  IncGeo_WardNameNew                      359036 non-null  object
 20  Easting_m                               160205 non-null  float64
 21  Northing_m                              160205 non-null  float64
 22  Easting_rounded                         359042 non-null  int64
 23  Northing_rounded                        359042 non-null  int64
 24  Latitude                                160205 non-null  float64
 25  Longitude                               160205 non-null  float64
 26  FRS                                     359042 non-null  object
 27  IncidentStationGround                   359041 non-null  object
 28  FirstPumpArriving_AttendanceTime        359041 non-null  float64
 29  FirstPumpArriving_DeployedFromStation   359036 non-null  object
 30  SecondPumpArriving_AttendanceTime       139168 non-null  float64
 31  SecondPumpArriving_DeployedFromStation  139166 non-null  object
 32  NumStationsWithPumpsAttending           359042 non-null  float64
 33  NumPumpsAttending                       359042 non-null  float64
 34  PumpCount                               359042 non-null  float64
 35  PumpHoursRoundUp                        358956 non-null  float64
 36  Notional Cost (£)                       358956 non-null  float64
 37  NumCalls                                359041 non-null  float64
 38  ResourceMobilisationId                  359042 non-null  int64
 39  Resource_Code                           359042 non-null  object
 40  PerformanceReporting                    359042 non-null  object
 41  DateAndTimeMobilised                    359042 non-null  object
 42  DateAndTimeMobile                       357120 non-null  object
 43  DateAndTimeArrived                      359042 non-null  object
 44  TurnoutTimeSeconds                      357114 non-null  float64
 45  TravelTimeSeconds                       357106 non-null  float64
 46  AttendanceTimeSeconds                   359042 non-null  int64
 47  DateAndTimeLeft                         358883 non-null  object
 48  DeployedFromStation_Code                359037 non-null  object
 49  DeployedFromStation_Name                359037 non-null  object
 50  DeployedFromLocation                    358777 non-null  object
 51  PumpOrder                               359042 non-null  int64
 52  PlusCode_Code                           359042 non-null  object
 53  PlusCode_Description                    359042 non-null  object
 54  DelayCodeId                             98075 non-null   float64
 55  DelayCode_Description                   98075 non-null   object
 56  DateOfCall_bis                          359042 non-null  datetime64[ns]
 57  MinuteOfCall                            359042 non-null  int32
dtypes: datetime64[ns](1), float64(15), int32(1), int64(9), object(32)
memory usage: 160.2+ MB

In [10]:
Final_1.drop(['TimeOfCall','DelayCode_Description','UPRN','USRN'], axis=1,inplace=True)
Final_1.drop(['FRS','PerformanceReporting','Postcode_full','DateAndTimeMobilised',
             'DateAndTimeMobile','DateAndTimeArrived'], axis=1,inplace=True)
Final_1.drop(['PumpOrder','PlusCode_Code','PlusCode_Description','Easting_m','Northing_m'], axis=1,inplace=True)
Final_1.drop(['PumpHoursRoundUp','Notional Cost (£)'], axis=1,inplace=True)
Final_1.drop(['FirstPumpArriving_AttendanceTime','SecondPumpArriving_AttendanceTime',
              'SecondPumpArriving_DeployedFromStation'], axis=1,inplace=True)
Final_1.drop(['PropertyType','SpecialServiceType','Postcode_district','IncGeo_WardCode','IncGeo_WardName',
             'IncGeo_WardNameNew'], axis=1,inplace=True)
Final_1.drop(['IncGeo_BoroughName'], axis=1,inplace=True)
Final_1.drop(['FirstPumpArriving_DeployedFromStation','DeployedFromStation_Code','DeployedFromLocation'], axis=1,inplace=True)
Final_1.drop(['DateAndTimeLeft'], axis=1,inplace=True)

In [11]:
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 359042 entries, 0 to 359041
Data columns (total 27 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   IncidentNumber                 359042 non-null  object
 1   CalYear                        359042 non-null  int64
 2   HourOfCall                     359042 non-null  int64
 3   IncidentGroup                  359042 non-null  object
 4   StopCodeDescription            359042 non-null  object
 5   PropertyCategory               359042 non-null  object
 6   AddressQualifier               359042 non-null  object
 7   IncGeo_BoroughCode             359042 non-null  object
 8   ProperCase                     359042 non-null  object
 9   Easting_rounded                359042 non-null  int64
 10  Northing_rounded               359042 non-null  int64
 11  Latitude                       160205 non-null  float64
 12  Longitude                      160205 non-null  float64
 13  IncidentStationGround          359041 non-null  object
 14  NumStationsWithPumpsAttending  359042 non-null  float64
 15  NumPumpsAttending              359042 non-null  float64
 16  PumpCount                      359042 non-null  float64
 17  NumCalls                       359041 non-null  float64
 18  ResourceMobilisationId         359042 non-null  int64
 19  Resource_Code                  359042 non-null  object
 20  TurnoutTimeSeconds             357114 non-null  float64
 21  TravelTimeSeconds              357106 non-null  float64
 22  AttendanceTimeSeconds          359042 non-null  int64
 23  DeployedFromStation_Name       359037 non-null  object
 24  DelayCodeId                    98075 non-null   float64
 25  DateOfCall_bis                 359042 non-null  datetime64[ns]
 26  MinuteOfCall                   359042 non-null  int32
dtypes: datetime64[ns](1), float64(9), int32(1), int64(6), object(10)
memory usage: 75.3+ MB

In [12]:
Final_1['DelayCodeId_bis']=Final_1['DelayCodeId'].fillna(12)
Final_1.drop(['DelayCodeId'], axis=1,inplace=True)

In [13]:
Final_1.drop(['StopCodeDescription'], axis=1,inplace=True)

In [14]:
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 359042 entries, 0 to 359041
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   IncidentNumber                 359042 non-null  object
 1   CalYear                        359042 non-null  int64
 2   HourOfCall                     359042 non-null  int64
 3   IncidentGroup                  359042 non-null  object
 4   PropertyCategory               359042 non-null  object
 5   AddressQualifier               359042 non-null  object
 6   IncGeo_BoroughCode             359042 non-null  object
 7   ProperCase                     359042 non-null  object
 8   Easting_rounded                359042 non-null  int64
 9   Northing_rounded               359042 non-null  int64
 10  Latitude                       160205 non-null  float64
 11  Longitude                      160205 non-null  float64
 12  IncidentStationGround          359041 non-null  object
 13  NumStationsWithPumpsAttending  359042 non-null  float64
 14  NumPumpsAttending              359042 non-null  float64
 15  PumpCount                      359042 non-null  float64
 16  NumCalls                       359041 non-null  float64
 17  ResourceMobilisationId         359042 non-null  int64
 18  Resource_Code                  359042 non-null  object
 19  TurnoutTimeSeconds             357114 non-null  float64
 20  TravelTimeSeconds              357106 non-null  float64
 21  AttendanceTimeSeconds          359042 non-null  int64
 22  DeployedFromStation_Name       359037 non-null  object
 23  DateOfCall_bis                 359042 non-null  datetime64[ns]
 24  MinuteOfCall                   359042 non-null  int32
 25  DelayCodeId_bis                359042 non-null  float64
dtypes: datetime64[ns](1), float64(9), int32(1), int64(6), object(9)
memory usage: 72.6+ MB

In [15]:
Final_1['IncidentGroup']=Final_1['IncidentGroup'].replace(['False Alarm','Fire','Special Service'],[1,2,3])

In [16]:
Final_1.drop(['PropertyCategory','AddressQualifier'], axis=1,inplace=True)

In [17]:
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 359042 entries, 0 to 359041
Data columns (total 24 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   IncidentNumber                 359042 non-null  object
 1   CalYear                        359042 non-null  int64
 2   HourOfCall                     359042 non-null  int64
 3   IncidentGroup                  359042 non-null  int64
 4   IncGeo_BoroughCode             359042 non-null  object
 5   ProperCase                     359042 non-null  object
 6   Easting_rounded                359042 non-null  int64
 7   Northing_rounded               359042 non-null  int64
 8   Latitude                       160205 non-null  float64
 9   Longitude                      160205 non-null  float64
 10  IncidentStationGround          359041 non-null  object
 11  NumStationsWithPumpsAttending  359042 non-null  float64
 12  NumPumpsAttending              359042 non-null  float64
 13  PumpCount                      359042 non-null  float64
 14  NumCalls                       359041 non-null  float64
 15  ResourceMobilisationId         359042 non-null  int64
 16  Resource_Code                  359042 non-null  object
 17  TurnoutTimeSeconds             357114 non-null  float64
 18  TravelTimeSeconds              357106 non-null  float64
 19  AttendanceTimeSeconds          359042 non-null  int64
 20  DeployedFromStation_Name       359037 non-null  object
 21  DateOfCall_bis                 359042 non-null  datetime64[ns]
 22  MinuteOfCall                   359042 non-null  int32
 23  DelayCodeId_bis                359042 non-null  float64
dtypes: datetime64[ns](1), float64(9), int32(1), int64(7), object(6)
memory usage: 67.1+ MB

In [18]:
Final_1.drop(['ProperCase','IncidentStationGround'], axis=1,inplace=True)

In [19]:
from datetime import date
Final_1['Joursem']=Final_1['DateOfCall_bis'].dt.weekday

In [20]:
Final_1['mois']=Final_1['DateOfCall_bis'].dt.month
Final_1['jour']=Final_1['DateOfCall_bis'].dt.day

In [21]:
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 359042 entries, 0 to 359041
Data columns (total 25 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   IncidentNumber                 359042 non-null  object
 1   CalYear                        359042 non-null  int64
 2   HourOfCall                     359042 non-null  int64
 3   IncidentGroup                  359042 non-null  int64
 4   IncGeo_BoroughCode             359042 non-null  object
 5   Easting_rounded                359042 non-null  int64
 6   Northing_rounded               359042 non-null  int64
 7   Latitude                       160205 non-null  float64
 8   Longitude                      160205 non-null  float64
 9   NumStationsWithPumpsAttending  359042 non-null  float64
 10  NumPumpsAttending              359042 non-null  float64
 11  PumpCount                      359042 non-null  float64
 12  NumCalls                       359041 non-null  float64
 13  ResourceMobilisationId         359042 non-null  int64
 14  Resource_Code                  359042 non-null  object
 15  TurnoutTimeSeconds             357114 non-null  float64
 16  TravelTimeSeconds              357106 non-null  float64
 17  AttendanceTimeSeconds          359042 non-null  int64
 18  DeployedFromStation_Name       359037 non-null  object
 19  DateOfCall_bis                 359042 non-null  datetime64[ns]
 20  MinuteOfCall                   359042 non-null  int32
 21  DelayCodeId_bis                359042 non-null  float64
 22  Joursem                        359042 non-null  int64
 23  mois                           359042 non-null  int64
 24  jour                           359042 non-null  int64
dtypes: datetime64[ns](1), float64(9), int32(1), int64(10), object(4)
memory usage: 69.9+ MB

In [22]:
Calendrier=pd.read_csv(r"C:\Users\agrabia\Documents\Formation\Projet/London_Pompyer_Calendrier.csv", sep=';')
Calendrier['DateOfCall_bis'] = pd.to_datetime(Calendrier['DateOfCall_bis'])

C:\Users\agrabia\AppData\Local\Temp\ipykernel_18276\1042827561.py:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  Calendrier['DateOfCall_bis'] = pd.to_datetime(Calendrier['DateOfCall_bis'])

In [23]:
Calendrier.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1247 entries, 0 to 1246
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DateOfCall_bis            1247 non-null   datetime64[ns]
 1   jour ferie                1247 non-null   int64
 2   vacances                  1247 non-null   int64
 3   COVID (fermeture ecoles)  1247 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 39.1 KB

In [24]:
Final_1=Final_1.merge(right=Calendrier, on='DateOfCall_bis')
Final_1=Final_1.merge(right=Coordonnees_brigade, on='DeployedFromStation_Name')
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 348679 entries, 0 to 348678
Data columns (total 31 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   IncidentNumber                 348679 non-null  object
 1   CalYear                        348679 non-null  int64
 2   HourOfCall                     348679 non-null  int64
 3   IncidentGroup                  348679 non-null  int64
 4   IncGeo_BoroughCode             348679 non-null  object
 5   Easting_rounded                348679 non-null  int64
 6   Northing_rounded               348679 non-null  int64
 7   Latitude_x                     155892 non-null  float64
 8   Longitude_x                    155892 non-null  float64
 9   NumStationsWithPumpsAttending  348679 non-null  float64
 10  NumPumpsAttending              348679 non-null  float64
 11  PumpCount                      348679 non-null  float64
 12  NumCalls                       348678 non-null  float64
 13  ResourceMobilisationId         348679 non-null  int64
 14  Resource_Code                  348679 non-null  object
 15  TurnoutTimeSeconds             346819 non-null  float64
 16  TravelTimeSeconds              346812 non-null  float64
 17  AttendanceTimeSeconds          348679 non-null  int64
 18  DeployedFromStation_Name       348679 non-null  object
 19  DateOfCall_bis                 348679 non-null  datetime64[ns]
 20  MinuteOfCall                   348679 non-null  int32
 21  DelayCodeId_bis                348679 non-null  float64
 22  Joursem                        348679 non-null  int64
 23  mois                           348679 non-null  int64
 24  jour                           348679 non-null  int64
 25  jour ferie                     348679 non-null  int64
 26  vacances                       348679 non-null  int64
 27  COVID (fermeture ecoles)       348679 non-null  int64
 28  Adresse                        348679 non-null  object
 29  Latitude_y                     348679 non-null  float64
 30  Longitude_y                    348679 non-null  float64
dtypes: datetime64[ns](1), float64(11), int32(1), int64(13), object(5)
memory usage: 83.8+ MB

In [25]:
Final_1.drop(['Resource_Code'], axis=1,inplace=True)
Final_1.drop(['Adresse'], axis=1,inplace=True)
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 348679 entries, 0 to 348678
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   IncidentNumber                 348679 non-null  object
 1   CalYear                        348679 non-null  int64
 2   HourOfCall                     348679 non-null  int64
 3   IncidentGroup                  348679 non-null  int64
 4   IncGeo_BoroughCode             348679 non-null  object
 5   Easting_rounded                348679 non-null  int64
 6   Northing_rounded               348679 non-null  int64
 7   Latitude_x                     155892 non-null  float64
 8   Longitude_x                    155892 non-null  float64
 9   NumStationsWithPumpsAttending  348679 non-null  float64
 10  NumPumpsAttending              348679 non-null  float64
 11  PumpCount                      348679 non-null  float64
 12  NumCalls                       348678 non-null  float64
 13  ResourceMobilisationId         348679 non-null  int64
 14  TurnoutTimeSeconds             346819 non-null  float64
 15  TravelTimeSeconds              346812 non-null  float64
 16  AttendanceTimeSeconds          348679 non-null  int64
 17  DeployedFromStation_Name       348679 non-null  object
 18  DateOfCall_bis                 348679 non-null  datetime64[ns]
 19  MinuteOfCall                   348679 non-null  int32
 20  DelayCodeId_bis                348679 non-null  float64
 21  Joursem                        348679 non-null  int64
 22  mois                           348679 non-null  int64
 23  jour                           348679 non-null  int64
 24  jour ferie                     348679 non-null  int64
 25  vacances                       348679 non-null  int64
 26  COVID (fermeture ecoles)       348679 non-null  int64
 27  Latitude_y                     348679 non-null  float64
 28  Longitude_y                    348679 non-null  float64
dtypes: datetime64[ns](1), float64(11), int32(1), int64(13), object(3)
memory usage: 78.5+ MB

In [26]:
pip install bng

Requirement already satisfied: bng in c:\users\agrabia\appdata\local\anaconda3\lib\site-packages (1.0.5)
Note: you may need to restart the kernel to use updated packages.

In [27]:
pip install pyproj

Requirement already satisfied: pyproj in c:\users\agrabia\appdata\local\anaconda3\lib\site-packages (3.6.1)
Requirement already satisfied: certifi in c:\users\agrabia\appdata\local\anaconda3\lib\site-packages (from pyproj) (2023.5.7)
Note: you may need to restart the kernel to use updated packages.

In [28]:
import bng
import pyproj
crs_british = pyproj.Proj(init='EPSG:27700')
crs_wgs84 = pyproj.Proj(init='EPSG:4326')
Final_1['long'], Final_1['lat'] = pyproj.transform(crs_british, crs_wgs84, Final_1['Easting_rounded'], Final_1['Northing_rounded'])

C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\agrabia\AppData\Local\Temp\ipykernel_18276\2879933218.py:5: FutureWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  Final_1['long'], Final_1['lat'] = pyproj.transform(crs_british, crs_wgs84, Final_1['Easting_rounded'], Final_1['Northing_rounded'])

In [89]:
Final_1.head()

,IncidentNumber,CalYear,HourOfCall,IncidentGroup,IncGeo_BoroughCode,Easting_rounded,Northing_rounded,Latitude_x,Longitude_x,NumStationsWithPumpsAttending,...,Joursem,mois,jour,jour ferie,vacances,COVID (fermeture ecoles),Latitude_y,Longitude_y,long,lat
0,000003-01012020,2020,0,2,E09000017,506750,181550,NaN,NaN,1.0,...,2,1,1,1,1,0,51.532268,-0.451897,-0.462727,51.522788
1,000037-01012020,2020,0,2,E09000017,507750,184650,51.550662,-0.447747,1.0,...,2,1,1,1,1,0,51.532268,-0.451897,-0.447371,51.550461
2,000177-01012020,2020,4,2,E09000017,505250,184450,51.549455,-0.482830,1.0,...,2,1,1,1,1,0,51.532268,-0.451897,-0.483473,51.549135
3,000206-01012020,2020,7,1,E09000017,508850,184550,51.549674,-0.432116,2.0,...,2,1,1,1,1,0,51.532268,-0.451897,-0.431544,51.549352
4,000294-01012020,2020,12,3,E09000017,507450,182550,51.532061,-0.452014,1.0,...,2,1,1,1,1,0,51.532268,-0.451897,-0.452337,51.531643

In [29]:
pip install geopy

Requirement already satisfied: geopy in c:\users\agrabia\appdata\local\anaconda3\lib\site-packages (2.4.0)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\agrabia\appdata\local\anaconda3\lib\site-packages (from geopy) (2.0)
Note: you may need to restart the kernel to use updated packages.

In [30]:
import geopy.distance
def calc_orthodromic(row):
    try:
        return geopy.distance.geodesic(row["XY"], row["XY_cas"]).km
    except:
        return np.NaN

Final_1['XY'] = list(zip(Final_1["lat"], Final_1["long"]))
Final_1['XY_cas'] = list(zip(Final_1["Latitude_y"], Final_1["Longitude_y"]))

Final_1['distance'] = Final_1.apply(calc_orthodromic, axis=1)

In [31]:
Final_1.drop(['NumStationsWithPumpsAttending','NumPumpsAttending','PumpCount','Latitude_x',
             'Longitude_x','Latitude_y','Longitude_y','long','lat',
             'XY','XY_cas'], axis=1,inplace=True)
Final_1.head()

,IncidentNumber,CalYear,HourOfCall,IncidentGroup,IncGeo_BoroughCode,Easting_rounded,Northing_rounded,NumCalls,ResourceMobilisationId,TurnoutTimeSeconds,...,DateOfCall_bis,MinuteOfCall,DelayCodeId_bis,Joursem,mois,jour,jour ferie,vacances,COVID (fermeture ecoles),distance
0,000003-01012020,2020,0,2,E09000017,506750,181550,3.0,5547476,78.0,...,2020-01-01,6,12.0,2,1,1,1,1,0,1.295103
1,000037-01012020,2020,0,2,E09000017,507750,184650,1.0,5547511,118.0,...,2020-01-01,27,9.0,2,1,1,1,1,0,2.048409
2,000177-01012020,2020,4,2,E09000017,505250,184450,1.0,5547713,102.0,...,2020-01-01,56,12.0,2,1,1,1,1,0,2.884629
3,000206-01012020,2020,7,1,E09000017,508850,184550,1.0,5547751,106.0,...,2020-01-01,13,12.0,2,1,1,1,1,0,2.367860
4,000294-01012020,2020,12,3,E09000017,507450,182550,1.0,5547874,12.0,...,2020-01-01,40,12.0,2,1,1,1,1,0,0.075857

In [32]:
Final_1.drop(['Easting_rounded','Northing_rounded','NumCalls','ResourceMobilisationId',
             'TurnoutTimeSeconds','AttendanceTimeSeconds'], axis=1,inplace=True)
Final_1.head()

,IncidentNumber,CalYear,HourOfCall,IncidentGroup,IncGeo_BoroughCode,TravelTimeSeconds,DeployedFromStation_Name,DateOfCall_bis,MinuteOfCall,DelayCodeId_bis,Joursem,mois,jour,jour ferie,vacances,COVID (fermeture ecoles),distance
0,000003-01012020,2020,0,2,E09000017,246.0,Hillingdon,2020-01-01,6,12.0,2,1,1,1,1,0,1.295103
1,000037-01012020,2020,0,2,E09000017,255.0,Hillingdon,2020-01-01,27,9.0,2,1,1,1,1,0,2.048409
2,000177-01012020,2020,4,2,E09000017,236.0,Hillingdon,2020-01-01,56,12.0,2,1,1,1,1,0,2.884629
3,000206-01012020,2020,7,1,E09000017,204.0,Hillingdon,2020-01-01,13,12.0,2,1,1,1,1,0,2.367860
4,000294-01012020,2020,12,3,E09000017,1.0,Hillingdon,2020-01-01,40,12.0,2,1,1,1,1,0,0.075857

In [33]:
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 348679 entries, 0 to 348678
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   IncidentNumber            348679 non-null  object
 1   CalYear                   348679 non-null  int64
 2   HourOfCall                348679 non-null  int64
 3   IncidentGroup             348679 non-null  int64
 4   IncGeo_BoroughCode        348679 non-null  object
 5   TravelTimeSeconds         346812 non-null  float64
 6   DeployedFromStation_Name  348679 non-null  object
 7   DateOfCall_bis            348679 non-null  datetime64[ns]
 8   MinuteOfCall              348679 non-null  int32
 9   DelayCodeId_bis           348679 non-null  float64
 10  Joursem                   348679 non-null  int64
 11  mois                      348679 non-null  int64
 12  jour                      348679 non-null  int64
 13  jour ferie                348679 non-null  int64
 14  vacances                  348679 non-null  int64
 15  COVID (fermeture ecoles)  348679 non-null  int64
 16  distance                  348679 non-null  float64
dtypes: datetime64[ns](1), float64(3), int32(1), int64(9), object(3)
memory usage: 46.6+ MB

In [34]:
Final_1=Final_1.dropna()
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 346812 entries, 0 to 348677
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   IncidentNumber            346812 non-null  object
 1   CalYear                   346812 non-null  int64
 2   HourOfCall                346812 non-null  int64
 3   IncidentGroup             346812 non-null  int64
 4   IncGeo_BoroughCode        346812 non-null  object
 5   TravelTimeSeconds         346812 non-null  float64
 6   DeployedFromStation_Name  346812 non-null  object
 7   DateOfCall_bis            346812 non-null  datetime64[ns]
 8   MinuteOfCall              346812 non-null  int32
 9   DelayCodeId_bis           346812 non-null  float64
 10  Joursem                   346812 non-null  int64
 11  mois                      346812 non-null  int64
 12  jour                      346812 non-null  int64
 13  jour ferie                346812 non-null  int64
 14  vacances                  346812 non-null  int64
 15  COVID (fermeture ecoles)  346812 non-null  int64
 16  distance                  346812 non-null  float64
dtypes: datetime64[ns](1), float64(3), int32(1), int64(9), object(3)
memory usage: 46.3+ MB

In [35]:
Final_1['index_col'] = Final_1.index  
def mean_without_self(group):     
    return group.apply(lambda row: group[group['index_col'] != row['index_col']]['TravelTimeSeconds'].mean(), axis=1)  
new_column = Final_1.groupby(['DeployedFromStation_Name', 'HourOfCall']).apply(mean_without_self).reset_index(level=0, drop=True)   
Final_1['average_time_of_arrival_Station_Hour'] = new_column.reset_index(level=0, drop=True)
Final_1.drop(['index_col'], axis=1,inplace=True)
Final_1.head()

,IncidentNumber,CalYear,HourOfCall,IncidentGroup,IncGeo_BoroughCode,TravelTimeSeconds,DeployedFromStation_Name,DateOfCall_bis,MinuteOfCall,DelayCodeId_bis,Joursem,mois,jour,jour ferie,vacances,COVID (fermeture ecoles),distance,average_time_of_arrival_Station_Hour
0,000003-01012020,2020,0,2,E09000017,246.0,Hillingdon,2020-01-01,6,12.0,2,1,1,1,1,0,1.295103,247.809917
1,000037-01012020,2020,0,2,E09000017,255.0,Hillingdon,2020-01-01,27,9.0,2,1,1,1,1,0,2.048409,247.735537
2,000177-01012020,2020,4,2,E09000017,236.0,Hillingdon,2020-01-01,56,12.0,2,1,1,1,1,0,2.884629,268.232877
3,000206-01012020,2020,7,1,E09000017,204.0,Hillingdon,2020-01-01,13,12.0,2,1,1,1,1,0,2.367860,267.365385
4,000294-01012020,2020,12,3,E09000017,1.0,Hillingdon,2020-01-01,40,12.0,2,1,1,1,1,0,0.075857,289.010695

In [36]:
Final_1['index_col'] = Final_1.index  
def mean_without_self(group):     
    return group.apply(lambda row: group[group['index_col'] != row['index_col']]['TravelTimeSeconds'].mean(), axis=1)  
new_column = Final_1.groupby(['IncGeo_BoroughCode', 'HourOfCall']).apply(mean_without_self).reset_index(level=0, drop=True)   
Final_1['average_time_of_arrival_Borough_Hour'] = new_column.reset_index(level=0, drop=True)
Final_1.drop(['index_col'], axis=1,inplace=True)
Final_1.head()

,IncidentNumber,CalYear,HourOfCall,IncidentGroup,IncGeo_BoroughCode,TravelTimeSeconds,DeployedFromStation_Name,DateOfCall_bis,MinuteOfCall,DelayCodeId_bis,Joursem,mois,jour,jour ferie,vacances,COVID (fermeture ecoles),distance,average_time_of_arrival_Station_Hour,average_time_of_arrival_Borough_Hour
0,000003-01012020,2020,0,2,E09000017,246.0,Hillingdon,2020-01-01,6,12.0,2,1,1,1,1,0,1.295103,247.809917,272.927114
1,000037-01012020,2020,0,2,E09000017,255.0,Hillingdon,2020-01-01,27,9.0,2,1,1,1,1,0,2.048409,247.735537,272.900875
2,000177-01012020,2020,4,2,E09000017,236.0,Hillingdon,2020-01-01,56,12.0,2,1,1,1,1,0,2.884629,268.232877,282.379630
3,000206-01012020,2020,7,1,E09000017,204.0,Hillingdon,2020-01-01,13,12.0,2,1,1,1,1,0,2.367860,267.365385,280.375000
4,000294-01012020,2020,12,3,E09000017,1.0,Hillingdon,2020-01-01,40,12.0,2,1,1,1,1,0,0.075857,289.010695,308.286656

In [37]:
Final_1.drop(['IncGeo_BoroughCode','DeployedFromStation_Name'], axis=1,inplace=True)
Final_1.head()

,IncidentNumber,CalYear,HourOfCall,IncidentGroup,TravelTimeSeconds,DateOfCall_bis,MinuteOfCall,DelayCodeId_bis,Joursem,mois,jour,jour ferie,vacances,COVID (fermeture ecoles),distance,average_time_of_arrival_Station_Hour,average_time_of_arrival_Borough_Hour
0,000003-01012020,2020,0,2,246.0,2020-01-01,6,12.0,2,1,1,1,1,0,1.295103,247.809917,272.927114
1,000037-01012020,2020,0,2,255.0,2020-01-01,27,9.0,2,1,1,1,1,0,2.048409,247.735537,272.900875
2,000177-01012020,2020,4,2,236.0,2020-01-01,56,12.0,2,1,1,1,1,0,2.884629,268.232877,282.379630
3,000206-01012020,2020,7,1,204.0,2020-01-01,13,12.0,2,1,1,1,1,0,2.367860,267.365385,280.375000
4,000294-01012020,2020,12,3,1.0,2020-01-01,40,12.0,2,1,1,1,1,0,0.075857,289.010695,308.286656

In [38]:
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 346812 entries, 0 to 348677
Data columns (total 17 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   IncidentNumber                        346812 non-null  object
 1   CalYear                               346812 non-null  int64
 2   HourOfCall                            346812 non-null  int64
 3   IncidentGroup                         346812 non-null  int64
 4   TravelTimeSeconds                     346812 non-null  float64
 5   DateOfCall_bis                        346812 non-null  datetime64[ns]
 6   MinuteOfCall                          346812 non-null  int32
 7   DelayCodeId_bis                       346812 non-null  float64
 8   Joursem                               346812 non-null  int64
 9   mois                                  346812 non-null  int64
 10  jour                                  346812 non-null  int64
 11  jour ferie                            346812 non-null  int64
 12  vacances                              346812 non-null  int64
 13  COVID (fermeture ecoles)              346812 non-null  int64
 14  distance                              346812 non-null  float64
 15  average_time_of_arrival_Station_Hour  346811 non-null  float64
 16  average_time_of_arrival_Borough_Hour  346812 non-null  float64
dtypes: datetime64[ns](1), float64(5), int32(1), int64(9), object(1)
memory usage: 46.3+ MB

In [46]:
Meteo=pd.read_excel(r"\Users\agrabia\Documents\Formation\Projet/london_weather2.xlsx")

In [47]:
Meteo.head()

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,icon
0,london,2020-01-01,7.0,2.7,5.4,6.5,1.4,4.5,3.6,88.2,...,92.8,5.4,8.8,0.7,0,NaN,2020-01-01T08:06:17,2020-01-01T16:01:35,0.20,rain
1,london,2020-01-02,10.6,7.0,8.9,10.6,4.9,8.0,6.7,85.7,...,93.2,17.9,12.3,1.1,1,NaN,2020-01-02T08:06:11,2020-01-02T16:02:38,0.23,rain
2,london,2020-01-03,10.6,5.6,8.7,10.6,3.1,7.3,5.4,80.2,...,68.8,23.7,12.4,1.1,1,NaN,2020-01-03T08:06:02,2020-01-03T16:03:44,0.25,rain
3,london,2020-01-04,8.6,4.0,6.6,6.8,1.3,4.0,3.1,78.4,...,77.5,35.7,15.1,1.3,1,NaN,2020-01-04T08:05:49,2020-01-04T16:04:53,0.30,partly-cloudy-day
4,london,2020-01-05,9.0,6.6,7.9,6.5,4.2,5.6,4.7,80.1,...,95.6,38.8,11.8,1.0,1,NaN,2020-01-05T08:05:34,2020-01-05T16:06:04,0.33,cloudy

In [48]:
Meteo['DateOfCall_bis'] = pd.to_datetime(Meteo['datetime'])
Meteo.drop(['datetime'], axis=1,inplace=True)
Meteo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 30 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              1440 non-null   object
 1   tempmax           1440 non-null   float64
 2   tempmin           1440 non-null   float64
 3   temp              1440 non-null   float64
 4   feelslikemax      1440 non-null   float64
 5   feelslikemin      1440 non-null   float64
 6   feelslike         1440 non-null   float64
 7   dew               1440 non-null   float64
 8   humidity          1440 non-null   float64
 9   precip            1440 non-null   float64
 10  precipprob        1440 non-null   float64
 11  precipcover       1440 non-null   float64
 12  preciptype        900 non-null    object
 13  snow              1440 non-null   float64
 14  snowdepth         1440 non-null   float64
 15  windgust          1053 non-null   float64
 16  windspeed         1440 non-null   float64
 17  winddir           1440 non-null   float64
 18  sealevelpressure  1439 non-null   float64
 19  cloudcover        1440 non-null   float64
 20  visibility        1440 non-null   float64
 21  solarradiation    1440 non-null   float64
 22  solarenergy       1440 non-null   float64
 23  uvindex           1440 non-null   int64
 24  severerisk        700 non-null    float64
 25  sunrise           1440 non-null   object
 26  sunset            1440 non-null   object
 27  moonphase         1440 non-null   float64
 28  icon              1440 non-null   object
 29  DateOfCall_bis    1440 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(23), int64(1), object(5)
memory usage: 337.6+ KB

In [49]:
Meteo.drop(['name','feelslikemax','feelslikemin','feelslike','dew','humidity','precipprob',
           'precipcover','preciptype','snowdepth','windgust','windspeed','winddir','sealevelpressure',
           'cloudcover','visibility','solarradiation','solarenergy','uvindex','severerisk',
           'sunrise','sunset','moonphase','icon'], axis=1,inplace=True)

In [50]:
Meteo.head()

   tempmax  tempmin  temp  precip  snow DateOfCall_bis
0      7.0      2.7   5.4   0.001   0.0     2020-01-01
1     10.6      7.0   8.9   0.001   0.0     2020-01-02
2     10.6      5.6   8.7   1.007   0.0     2020-01-03
3      8.6      4.0   6.6   0.000   0.0     2020-01-04
4      9.0      6.6   7.9   0.000   0.0     2020-01-05

In [51]:
Final_1=Final_1.merge(right=Meteo, on='DateOfCall_bis')
Final_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 346812 entries, 0 to 346811
Data columns (total 22 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   IncidentNumber                        346812 non-null  object
 1   CalYear                               346812 non-null  int64
 2   HourOfCall                            346812 non-null  int64
 3   IncidentGroup                         346812 non-null  int64
 4   TravelTimeSeconds                     346812 non-null  float64
 5   DateOfCall_bis                        346812 non-null  datetime64[ns]
 6   MinuteOfCall                          346812 non-null  int32
 7   DelayCodeId_bis                       346812 non-null  float64
 8   Joursem                               346812 non-null  int64
 9   mois                                  346812 non-null  int64
 10  jour                                  346812 non-null  int64
 11  jour ferie                            346812 non-null  int64
 12  vacances                              346812 non-null  int64
 13  COVID (fermeture ecoles)              346812 non-null  int64
 14  distance                              346812 non-null  float64
 15  average_time_of_arrival_Station_Hour  346811 non-null  float64
 16  average_time_of_arrival_Borough_Hour  346812 non-null  float64
 17  tempmax                               346812 non-null  float64
 18  tempmin                               346812 non-null  float64
 19  temp                                  346812 non-null  float64
 20  precip                                346812 non-null  float64
 21  snow                                  346812 non-null  float64
dtypes: datetime64[ns](1), float64(10), int32(1), int64(9), object(1)
memory usage: 59.5+ MB

In [52]:
Final_1.to_csv (r"C:\Users\agrabia\Documents\Formation\Projet/Final_1_corrt.csv", index = False, header=True)